[project]
name = "python-server"
version = "0.1.0"
description = "AI-powered Python backend with speech, vision, and 3D model generation."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.11",
    "firebase-admin>=6.7.0",
    "google-genai>=1.5.0",
    "litellm>=1.63.11",
]
